let name = 'Coding is great';
console.log(name);
let StudentCount = 0;
console.log(StudentCount); 
name = 'Coding is not easy, but still great';
console.log(name);
StudentCount = 14;
console.log(StudentCount);
change = name.toLowerCase();
console.log(StudentCount + 1);